### ISSUE TITLE
setup/fuzz - AddressSanitizer: SEGV /__w/onefuzz-notification/onefuzz-notification/simple-libfuzzer/simple.c:23:27 in LLVMFuzzerTestOneInput

### ISSUE THREAD

**Issue by mrragava** [mrragava/onefuzz-notification#3]
## Files

* input: [crash-ad8d48a497fd3cd2775f6b55230ea91a61e0b7a8](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-crashes-032590c6e8ea524cb32942a29c898a62&filename=crash-ad8d48a497fd3cd2775f6b55230ea91a61e0b7a8)
* exe: [setup/fuzz]( https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-setup-a7ec4edefc00598fae7acd01bc3d636f&filename=fuzz)
* report: [62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-unique-reports-032590c6e8ea524cb32942a29c898a62&filename=62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json)

## Repro

 `onefuzz --endpoint https://oefuzzingtest2instance.azurewebsites.net repro create_and_connect oft-unique-reports-032590c6e8ea524cb32942a29c898a62 62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json`

## Call Stack

```#0 0x54ac6e in LLVMFuzzerTestOneInput /__w/onefuzz-notification/onefuzz-notification/simple-libfuzzer/simple.c:23:27
#1 0x42e9f7 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x42e9f7)
#2 0x41ee8a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41ee8a)
#3 0x429e50 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x429e50)
#4 0x41cb52 in main (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41cb52)
#5 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
#6 0x41cbc9 in _start (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41cbc9)
```

## ASAN Log

```INFO: Seed: 2198428967
INFO: Loaded 1 modules   (21 inline 8-bit counters): 21 [0x788fb0, 0x788fc5), 
INFO: Loaded 1 PC tables (21 PCs): 21 [0x5664c8,0x566618), 
setup/fuzz: Running 1 inputs 1 time(s) each.
Running: /tmp/.tmpN5nqkv/crash-ad8d48a497fd3cd2775f6b55230ea91a61e0b7a8
AddressSanitizer:DEADLYSIGNAL
=================================================================
==6544==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000054ac6f bp 0x7fffffffd210 sp 0x7fffffffd000 T0)
==6544==The signal is caused by a WRITE memory access.
==6544==Hint: address points to the zero page.
    #0 0x54ac6e in LLVMFuzzerTestOneInput /__w/onefuzz-notification/onefuzz-notification/simple-libfuzzer/simple.c:23:27
    #1 0x42e9f7 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x42e9f7)
    #2 0x41ee8a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41ee8a)
    #3 0x429e50 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x429e50)
    #4 0x41cb52 in main (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41cb52)
    #5 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #6 0x41cbc9 in _start (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41cbc9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /__w/onefuzz-notification/onefuzz-notification/simple-libfuzzer/simple.c:23:27 in LLVMFuzzerTestOneInput
==6544==ABORTING
```

**Comment by mrragava** [comment]
Duplicate found.

* input: [crash-d9459e9afd0625dd9cc096cf2ceaac119ba2be5a](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-crashes-032590c6e8ea524cb32942a29c898a62&filename=crash-d9459e9afd0625dd9cc096cf2ceaac119ba2be5a)
* exe: [setup/fuzz]( https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-setup-a7ec4edefc00598fae7acd01bc3d636f&filename=fuzz)
* report: [62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-unique-reports-032590c6e8ea524cb32942a29c898a62&filename=62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [crash-d9459e9afd0625dd9cc096cf2ceaac119ba2be5a](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-crashes-032590c6e8ea524cb32942a29c898a62&filename=crash-d9459e9afd0625dd9cc096cf2ceaac119ba2be5a)
* exe: [setup/fuzz]( https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-setup-a7ec4edefc00598fae7acd01bc3d636f&filename=fuzz)
* report: [62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-unique-reports-032590c6e8ea524cb32942a29c898a62&filename=62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [crash-d9459e9afd0625dd9cc096cf2ceaac119ba2be5a](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-crashes-032590c6e8ea524cb32942a29c898a62&filename=crash-d9459e9afd0625dd9cc096cf2ceaac119ba2be5a)
* exe: [setup/fuzz]( https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-setup-a7ec4edefc00598fae7acd01bc3d636f&filename=fuzz)
* report: [62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-unique-reports-032590c6e8ea524cb32942a29c898a62&filename=62046c56c4d6ebf2da1919c4bd0396a545d654f02a6da1881334239550ce00db.json)
