### ISSUE TITLE
setup/fuzz - AddressSanitizer: FPE /__w/onefuzz-notification/onefuzz-notification/simple-libfuzzer/simple.c:58:32 in LLVMFuzzerTestOneInput

### ISSUE THREAD

**Issue by mrragava** [mrragava/onefuzz-notification#6]
## Files

* input: [crash-03cfa8f2ffeb9ca42c887a2c6b2b2a469b6971c7](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-crashes-032590c6e8ea524cb32942a29c898a62&filename=crash-03cfa8f2ffeb9ca42c887a2c6b2b2a469b6971c7)
* exe: [setup/fuzz]( https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-setup-a7ec4edefc00598fae7acd01bc3d636f&filename=fuzz)
* report: [01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-unique-reports-032590c6e8ea524cb32942a29c898a62&filename=01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json)

## Repro

 `onefuzz --endpoint https://oefuzzingtest2instance.azurewebsites.net repro create_and_connect oft-unique-reports-032590c6e8ea524cb32942a29c898a62 01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json`

## Call Stack

```#0 0x54b097 in LLVMFuzzerTestOneInput /__w/onefuzz-notification/onefuzz-notification/simple-libfuzzer/simple.c:58:32
#1 0x42e9f7 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x42e9f7)
#2 0x41ee8a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41ee8a)
#3 0x429e50 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x429e50)
#4 0x41cb52 in main (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41cb52)
#5 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
#6 0x41cbc9 in _start (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41cbc9)
```

## ASAN Log

```INFO: Seed: 1569872474
INFO: Loaded 1 modules   (21 inline 8-bit counters): 21 [0x788fb0, 0x788fc5), 
INFO: Loaded 1 PC tables (21 PCs): 21 [0x5664c8,0x566618), 
setup/fuzz: Running 1 inputs 1 time(s) each.
Running: /tmp/.tmpRg3lea/crash-03cfa8f2ffeb9ca42c887a2c6b2b2a469b6971c7
AddressSanitizer:DEADLYSIGNAL
=================================================================
==6870==ERROR: AddressSanitizer: FPE on unknown address 0x00000054b098 (pc 0x00000054b098 bp 0x7fffffffd210 sp 0x7fffffffd000 T0)
    #0 0x54b097 in LLVMFuzzerTestOneInput /__w/onefuzz-notification/onefuzz-notification/simple-libfuzzer/simple.c:58:32
    #1 0x42e9f7 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x42e9f7)
    #2 0x41ee8a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41ee8a)
    #3 0x429e50 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x429e50)
    #4 0x41cb52 in main (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41cb52)
    #5 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #6 0x41cbc9 in _start (/onefuzz/blob-containers/fuzz3rpz7enxyexcq/fuzz+0x41cbc9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE /__w/onefuzz-notification/onefuzz-notification/simple-libfuzzer/simple.c:58:32 in LLVMFuzzerTestOneInput
==6870==ABORTING
```

**Comment by mrragava** [comment]
Duplicate found.

* input: [crash-c376d7663ca8f2c9fbf1bf7f8f70e6c3c74fb8bf](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-crashes-032590c6e8ea524cb32942a29c898a62&filename=crash-c376d7663ca8f2c9fbf1bf7f8f70e6c3c74fb8bf)
* exe: [setup/fuzz]( https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-setup-a7ec4edefc00598fae7acd01bc3d636f&filename=fuzz)
* report: [01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-unique-reports-032590c6e8ea524cb32942a29c898a62&filename=01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [crash-c376d7663ca8f2c9fbf1bf7f8f70e6c3c74fb8bf](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-crashes-032590c6e8ea524cb32942a29c898a62&filename=crash-c376d7663ca8f2c9fbf1bf7f8f70e6c3c74fb8bf)
* exe: [setup/fuzz]( https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-setup-a7ec4edefc00598fae7acd01bc3d636f&filename=fuzz)
* report: [01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-unique-reports-032590c6e8ea524cb32942a29c898a62&filename=01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [crash-c376d7663ca8f2c9fbf1bf7f8f70e6c3c74fb8bf](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-crashes-032590c6e8ea524cb32942a29c898a62&filename=crash-c376d7663ca8f2c9fbf1bf7f8f70e6c3c74fb8bf)
* exe: [setup/fuzz]( https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-setup-a7ec4edefc00598fae7acd01bc3d636f&filename=fuzz)
* report: [01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json](https://oefuzzingtest2instance.azurewebsites.net/api/download?container=oft-unique-reports-032590c6e8ea524cb32942a29c898a62&filename=01052b9a77de89eaae5961216e21e335b38fe6e09860db37791d33a6e5260873.json)
